#! Commands that return lists of vectors:
#! FixedPoints(rep). . returns a list of vectors which form a basis for the fixed points of rep.
#!
#! FixedPoints. . . . . produce a basis for the fixed points of a module
#!
#! Improvement by Dan Christensen of code originally by Peter Webb.
#!

#! FixedQuotient(rep). . returns a list of vectors which form a basis for the augmentation ideal times rep.
#!
#! FixedQuotient(rep) returns a basis for augmentation ideal . module.
#! Handles trivial groups and zero-dimensional reps.
#!

#! SubFixedQuotient(rep, list of vectors). . returns a list of vectors
#! which form a basis for the augmentation ideal times the submodule
#! spanned by the list of vectors.
#!
#! SubFixedQuotient(rep, list of vecs)
#! returns a basis for augmentation ideal . submodule spanned by the vecs.
#! The span of the vecs must be a submodule, and this is not checked.
#! Handles trivial groups, zero-dimensional reps and empty u.
#!

#! BrauerTraceImage(rep, p-subgroup of rep.group). .returns a list of vectors that forms a basis for the sum of images of trace maps from fixed points of proper subgroups of the p-subgroup.
#! BrauerTraceImage(representation, p-subgroup of rep.group) returns a list
#! of vectors that is a basis for the sum of the images of traces from proper
#! subgroups of the p-group.  Written by Peter Webb June 2016.

#! Spin(rep, list of vectors) . . returns a basis for the
#! submodule generated by the vectors in the list
#!
#! Spin(rep, veclist) returns a basis for the submodule generated by the
#! vectors in veclist, which must be a list of vectors.
#!
#! GroupSpin is called by Spin(rep, veclist) when rep is a
#! group representation.
#! 

CoSpin(rep, list of vectors) . . .returns a basis for the largest submodule contained in the vector subspace spanned by the vectors in the list.

#! CoSpin(rep, veclist) . . .returns a basis for the largest submodule
#! contained in the vector subspace spanned by veclist.
#!
#! GroupCoSpin is called by CoSpin(rep, veclist) when rep is a
#! group representation.


InstallGlobalFunction( CoSpin, function(rep,veclist)
    return rep.operations.CoSpin(rep,veclist);
end );

InstallGlobalFunction( GroupCoSpin, function(rep,veclist)
    local u, fakerep;
    if Length(veclist)=0 then return(veclist); fi;
    u:=NullspaceMat(TransposedMat(veclist));
    if Length(u)=0 then
        return(IdentityMat(rep.dimension,rep.field));
    fi;
    fakerep:=ShallowCopy(rep);
    fakerep.genimages:=List(fakerep.genimages,TransposedMat);
    #Warning: fakerep is not a representation, because the genimages represent
    #the opposite group.
    u:= Spin(fakerep,u);
    u:= NullspaceMat(TransposedMat(u));
    return(List(u,x->x));
end );